# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Soot CI
on:
  workflow_dispatch:

jobs:
  BuildAndTest:
    name: Build and Test with java ${{ matrix.java_version }} [${{ 
      matrix.expander_leg }}]
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java_version: 11
          os: ubuntu-latest
          arch: arm64
          runner: ubuntu-24.04-arm
          expander_leg: ubuntu-latest-11-arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Java ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java_version }}
        architecture: ${{ matrix.arch }}
    - name: Build and test Java ${{ matrix.java_version }}
      run: |
        mvn -B --no-transfer-progress clean test -PJava${{ matrix.java_version }} -DdisableXmlReport=true


    timeout-minutes: 150
